namespace WebGPUWinRT
{
    struct GPUSupportedLimits {
        UInt32 maxTextureDimension1D;
        UInt32 maxTextureDimension2D;
        UInt32 maxTextureDimension3D;
        UInt32 maxTextureArrayLayers;
        UInt32 maxBindGroups;
        UInt32 maxBindGroupsPlusVertexBuffers;
        UInt32 maxBindingsPerBindGroup;
        UInt32 maxDynamicUniformBuffersPerPipelineLayout;
        UInt32 maxDynamicStorageBuffersPerPipelineLayout;
        UInt32 maxSampledTexturesPerShaderStage;
        UInt32 maxSamplersPerShaderStage;
        UInt32 maxStorageBuffersPerShaderStage;
        UInt32 maxStorageTexturesPerShaderStage;
        UInt32 maxUniformBuffersPerShaderStage;
        UInt64 maxUniformBufferBindingSize;
        UInt64 maxStorageBufferBindingSize;
        UInt32 minUniformBufferOffsetAlignment;
        UInt32 minStorageBufferOffsetAlignment;
        UInt32 maxVertexBuffers;
        UInt64 maxBufferSize;
        UInt32 maxVertexAttributes;
        UInt32 maxVertexBufferArrayStride;
        UInt32 maxInterStageShaderVariables;
        UInt32 maxColorAttachments;
        UInt32 maxColorAttachmentBytesPerSample;
        UInt32 maxComputeWorkgroupStorageSize;
        UInt32 maxComputeInvocationsPerWorkgroup;
        UInt32 maxComputeWorkgroupSizeX;
        UInt32 maxComputeWorkgroupSizeY;
        UInt32 maxComputeWorkgroupSizeZ;
        UInt32 maxComputeWorkgroupsPerDimension;
    };

    enum GPUFeature {
        Undefined = 0x00000000,
        DepthClipControl = 0x00000001,
        Depth32FloatStencil8 = 0x00000002,
        TimestampQuery = 0x00000003,
        TextureCompressionBC = 0x00000004,
        TextureCompressionBCSliced3D = 0x00000005,
        TextureCompressionETC2 = 0x00000006,
        TextureCompressionASTC = 0x00000007,
        TextureCompressionASTCSliced3D = 0x00000008,
        IndirectFirstInstance = 0x00000009,
        ShaderF16 = 0x0000000A,
        RG11B10UfloatRenderable = 0x0000000B,
        BGRA8UnormStorage = 0x0000000C,
        Float32Filterable = 0x0000000D,
        Float32Blendable = 0x0000000E,
        ClipDistances = 0x0000000F,
        DualSourceBlending = 0x00000010,
        // Force32 = 0x7FFFFFFF
    };

    interface IGPUAdapter
    {
        GPUSupportedLimits Limits { get; };
        IVectorView<GPUFeature> Features{ get; };
    }


    [default_interface]
    runtimeclass GPU
    {
        GPU();
	    IGPUAdapter RequestAdapter();
    }
}
