namespace WebGPUWinRT
{
    struct GPUSupportedLimits {
        UInt32 maxTextureDimension1D;
        UInt32 maxTextureDimension2D;
        UInt32 maxTextureDimension3D;
        UInt32 maxTextureArrayLayers;
        UInt32 maxBindGroups;
        UInt32 maxBindGroupsPlusVertexBuffers;
        UInt32 maxBindingsPerBindGroup;
        UInt32 maxDynamicUniformBuffersPerPipelineLayout;
        UInt32 maxDynamicStorageBuffersPerPipelineLayout;
        UInt32 maxSampledTexturesPerShaderStage;
        UInt32 maxSamplersPerShaderStage;
        UInt32 maxStorageBuffersPerShaderStage;
        UInt32 maxStorageTexturesPerShaderStage;
        UInt32 maxUniformBuffersPerShaderStage;
        UInt64 maxUniformBufferBindingSize;
        UInt64 maxStorageBufferBindingSize;
        UInt32 minUniformBufferOffsetAlignment;
        UInt32 minStorageBufferOffsetAlignment;
        UInt32 maxVertexBuffers;
        UInt64 maxBufferSize;
        UInt32 maxVertexAttributes;
        UInt32 maxVertexBufferArrayStride;
        UInt32 maxInterStageShaderVariables;
        UInt32 maxColorAttachments;
        UInt32 maxColorAttachmentBytesPerSample;
        UInt32 maxComputeWorkgroupStorageSize;
        UInt32 maxComputeInvocationsPerWorkgroup;
        UInt32 maxComputeWorkgroupSizeX;
        UInt32 maxComputeWorkgroupSizeY;
        UInt32 maxComputeWorkgroupSizeZ;
        UInt32 maxComputeWorkgroupsPerDimension;
    };

    enum GPUFeature {
        Undefined,
        DepthClipControl,
        Depth32FloatStencil8,
        TimestampQuery,
        TextureCompressionBC,
        TextureCompressionBCSliced3D,
        TextureCompressionETC2,
        TextureCompressionASTC,
        TextureCompressionASTCSliced3D,
        IndirectFirstInstance,
        ShaderF16,
        RG11B10UfloatRenderable,
        BGRA8UnormStorage,
        Float32Filterable,
        Float32Blendable,
        ClipDistances,
        DualSourceBlending,
        // Force32 = 0x7FFFFFFF
    };

    // Device Lost related types
    enum GPUDeviceLostReason {
        Unknown,
        Destroyed
    };

    struct GPUDeviceLostInfo {
        GPUDeviceLostReason Reason;
        String Message;
    };

    // Error types
    enum GPUErrorFilter {
        Validation,
        OutOfMemory,
        Internal
    };

    interface IGPUError
    {
        String Message { get; };
    };

    interface IGPUValidationError : IGPUError
    {
    };

    interface IGPUOutOfMemoryError : IGPUError
    {
    };

    interface IGPUInternalError : IGPUError
    {
    };

    // Buffer related types
    enum GPUBufferUsage {
        MapRead = 0x0001,
        MapWrite = 0x0002,
        CopySrc = 0x0004,
        CopyDst = 0x0008,
        Index = 0x0010,
        Vertex = 0x0020,
        Uniform = 0x0040,
        Storage = 0x0080,
        Indirect = 0x0100,
        QueryResolve = 0x0200
    };

    enum GPUBufferMapState {
        Unmapped,
        Pending,
        Mapped
    };

    enum GPUMapMode {
        Read = 0x0001,
        Write = 0x0002
    };

    struct GPUBufferDescriptor {
        String Label;
        UInt64 Size;
        UInt32 Usage; // GPUBufferUsage flags
        Boolean MappedAtCreation;
    };

    // Texture related types
    enum GPUTextureUsage {
        CopySrc = 0x01,
        CopyDst = 0x02,
        TextureBinding = 0x04,
        StorageBinding = 0x08,
        RenderAttachment = 0x10
    };

    enum GPUTextureDimension {
        _1D,
        _2D,
        _3D
    };

    enum GPUTextureFormat {
        // 8-bit formats
        R8Unorm,
        R8Snorm,
        R8Uint,
        R8Sint,
        // 16-bit formats
        R16Uint,
        R16Sint,
        R16Float,
        RG8Unorm,
        RG8Snorm,
        RG8Uint,
        RG8Sint,
        // 32-bit formats
        R32Uint,
        R32Sint,
        R32Float,
        RG16Uint,
        RG16Sint,
        RG16Float,
        RGBA8Unorm,
        RGBA8UnormSrgb,
        RGBA8Snorm,
        RGBA8Uint,
        RGBA8Sint,
        BGRA8Unorm,
        BGRA8UnormSrgb,
        // Packed 32-bit formats
        RGB9E5Ufloat,
        RGB10A2Unorm,
        RG11B10Ufloat,
        // 64-bit formats
        RG32Uint,
        RG32Sint,
        RG32Float,
        RGBA16Uint,
        RGBA16Sint,
        RGBA16Float,
        // 128-bit formats
        RGBA32Uint,
        RGBA32Sint,
        RGBA32Float,
        // Depth/stencil formats
        Stencil8,
        Depth16Unorm,
        Depth24Plus,
        Depth24PlusStencil8,
        Depth32Float,
        Depth32FloatStencil8
    };

    struct GPUExtent3D {
        UInt32 Width;
        UInt32 Height;
        UInt32 DepthOrArrayLayers;
    };

    struct GPUTextureDescriptor {
        String Label;
        GPUExtent3D Size;
        UInt32 MipLevelCount;
        UInt32 SampleCount;
        GPUTextureDimension Dimension;
        GPUTextureFormat Format;
        UInt32 Usage; // GPUTextureUsage flags
        IVectorView<GPUTextureFormat> ViewFormats;
    };

    // Sampler related types
    enum GPUAddressMode {
        ClampToEdge,
        Repeat,
        MirrorRepeat
    };

    enum GPUFilterMode {
        Nearest,
        Linear
    };

    enum GPUMipmapFilterMode {
        Nearest,
        Linear
    };

    enum GPUCompareFunction {
        Never,
        Less,
        Equal,
        LessEqual,
        Greater,
        NotEqual,
        GreaterEqual,
        Always
    };

    struct GPUSamplerDescriptor {
        String Label;
        GPUAddressMode AddressModeU;
        GPUAddressMode AddressModeV;
        GPUAddressMode AddressModeW;
        GPUFilterMode MagFilter;
        GPUFilterMode MinFilter;
        GPUMipmapFilterMode MipmapFilter;
        Single LodMinClamp;
        Single LodMaxClamp;
        GPUCompareFunction Compare;
        UInt16 MaxAnisotropy;
    };

    // Shader related types
    struct GPUShaderModuleDescriptor {
        String Label;
        String Code;
    };

    // Pipeline related types
    [default_interface]
    runtimeclass GPUPipelineLayoutDescriptor
    {
        GPUPipelineLayoutDescriptor();
        String Label;
        IVectorView<IGPUBindGroupLayout> BindGroupLayouts;
    };

    [default_interface]
    runtimeclass GPUComputePipelineDescriptor
    {
        GPUComputePipelineDescriptor();
        String Label;
        IGPUPipelineLayout Layout;
        String EntryPoint;
        IGPUShaderModule Module;
        // Constants would be a map-like structure in WinRT
    };

    [default_interface]
    runtimeclass GPURenderPipelineDescriptor
    {
        GPURenderPipelineDescriptor();
        String Label;
        IGPUPipelineLayout Layout;
        // Additional fields from WebIDL spec will be added as needed
        // vertex, primitive, depthStencil, multisample, fragment
    };

    // Command related types
    struct GPUCommandEncoderDescriptor {
        String Label;
    };

    struct GPUQuerySetDescriptor {
        String Label;
        GPUQueryType Type;
        UInt32 Count;
    };

    enum GPUQueryType {
        Occlusion,
        Timestamp
    };

    // Bind group related types
    [default_interface]
    runtimeclass GPUBindGroupLayoutDescriptor
    {
        GPUBindGroupLayoutDescriptor();
        String Label;
        // Entries would be defined separately
    };

    [default_interface]
    runtimeclass GPUBindGroupDescriptor
    {
        GPUBindGroupDescriptor();
        String Label;
        IGPUBindGroupLayout Layout;
        // Entries would be defined separately
    };

    // Queue descriptor
    struct GPUQueueDescriptor {
        String Label;
    };

    // External texture descriptor
    struct GPUExternalTextureDescriptor {
        String Label;
        // Additional properties would be defined here
    };

    // Render bundle encoder descriptor
    struct GPURenderBundleEncoderDescriptor {
        String Label;
        IVectorView<GPUTextureFormat> ColorFormats;
        GPUTextureFormat DepthStencilFormat;
        UInt32 SampleCount;
        Boolean DepthReadOnly;
        Boolean StencilReadOnly;
    };

    // Interface declarations for GPU objects
    interface IGPUBuffer : Windows.Foundation.IClosable
    {
        UInt64 Size { get; };
        UInt32 Usage { get; };
        GPUBufferMapState MapState { get; };
        String Label;

        Windows.Foundation.IAsyncAction MapAsync(UInt32 mode, UInt64 offset, UInt64 size);
        Windows.Storage.Streams.IBuffer GetMappedRange(UInt64 offset, UInt64 size);
        void Unmap();
    };

    interface IGPUTexture : Windows.Foundation.IClosable
    {
        UInt32 Width { get; };
        UInt32 Height { get; };
        UInt32 DepthOrArrayLayers { get; };
        UInt32 MipLevelCount { get; };
        UInt32 SampleCount { get; };
        GPUTextureDimension Dimension { get; };
        GPUTextureFormat Format { get; };
        UInt32 Usage { get; };
        String Label;

        IGPUTextureView CreateView();
        IGPUTextureView CreateViewWithDescriptor(GPUTextureViewDescriptor descriptor);
    };

    interface IGPUTextureView
    {
        String Label;
    };

    interface IGPUSampler
    {
        String Label;
    };

    interface IGPUExternalTexture
    {
        String Label;
    };

    interface IGPUShaderModule
    {
        String Label;
        Windows.Foundation.IAsyncOperation<IGPUCompilationInfo> GetCompilationInfo();
    };

    interface IGPUCompilationInfo
    {
        IVectorView<IGPUCompilationMessage> Messages { get; };
    };

    interface IGPUCompilationMessage
    {
        String Message { get; };
        // Additional properties would be defined here
    };

    interface IGPUBindGroupLayout
    {
        String Label;
    };

    interface IGPUPipelineLayout
    {
        String Label;
    };

    interface IGPUBindGroup
    {
        String Label;
    };

    interface IGPUComputePipeline
    {
        String Label;
        IGPUBindGroupLayout GetBindGroupLayout(UInt32 index);
    };

    interface IGPURenderPipeline
    {
        String Label;
        IGPUBindGroupLayout GetBindGroupLayout(UInt32 index);
    };

    interface IGPUCommandEncoder
    {
        String Label;

        IGPUComputePassEncoder BeginComputePass();
        IGPUComputePassEncoder BeginComputePassWithDescriptor(GPUComputePassDescriptor descriptor);
        
        IGPURenderPassEncoder BeginRenderPass(GPURenderPassDescriptor descriptor);
        
        void CopyBufferToBuffer(IGPUBuffer source, UInt64 sourceOffset, IGPUBuffer destination, UInt64 destinationOffset, UInt64 size);
        void CopyBufferToTexture(IGPUBuffer source, IGPUTexture destination, GPUExtent3D copySize);
        void CopyTextureToBuffer(IGPUTexture source, IGPUBuffer destination, GPUExtent3D copySize);
        void CopyTextureToTexture(IGPUTexture source, IGPUTexture destination, GPUExtent3D copySize);
        
        void ResolveQuerySet(IGPUQuerySet querySet, UInt32 firstQuery, UInt32 queryCount, IGPUBuffer destination, UInt64 destinationOffset);
        
        IGPUCommandBuffer Finish();
        IGPUCommandBuffer FinishWithDescriptor(GPUCommandBufferDescriptor descriptor);
    };

    interface IGPUCommandBuffer
    {
        String Label;
    };

    interface IGPUComputePassEncoder
    {
        String Label;
        
        void SetPipeline(IGPUComputePipeline pipeline);
        void SetBindGroup(UInt32 index, IGPUBindGroup bindGroup);
        void SetBindGroupWithOffsets(UInt32 index, IGPUBindGroup bindGroup, IVectorView<UInt32> dynamicOffsets);
        
        void DispatchWorkgroups(UInt32 workgroupCountX, UInt32 workgroupCountY, UInt32 workgroupCountZ);
        void DispatchWorkgroupsIndirect(IGPUBuffer indirectBuffer, UInt64 indirectOffset);
        
        void End();
    };

    interface IGPURenderPassEncoder
    {
        String Label;
        
        void SetPipeline(IGPURenderPipeline pipeline);
        void SetBindGroup(UInt32 index, IGPUBindGroup bindGroup);
        void SetBindGroupWithOffsets(UInt32 index, IGPUBindGroup bindGroup, IVectorView<UInt32> dynamicOffsets);
        
        void SetVertexBuffer(UInt32 slot, IGPUBuffer buffer, UInt64 offset, UInt64 size);
        void SetIndexBuffer(IGPUBuffer buffer, GPUIndexFormat format, UInt64 offset, UInt64 size);
        
        void Draw(UInt32 vertexCount, UInt32 instanceCount, UInt32 firstVertex, UInt32 firstInstance);
        void DrawIndexed(UInt32 indexCount, UInt32 instanceCount, UInt32 firstIndex, Int32 baseVertex, UInt32 firstInstance);
        void DrawIndirect(IGPUBuffer indirectBuffer, UInt64 indirectOffset);
        void DrawIndexedIndirect(IGPUBuffer indirectBuffer, UInt64 indirectOffset);
        
        void End();
    };

    interface IGPURenderBundleEncoder
    {
        String Label;
        
        void SetPipeline(IGPURenderPipeline pipeline);
        void SetBindGroup(UInt32 index, IGPUBindGroup bindGroup);
        void SetBindGroupWithOffsets(UInt32 index, IGPUBindGroup bindGroup, IVectorView<UInt32> dynamicOffsets);
        
        void SetVertexBuffer(UInt32 slot, IGPUBuffer buffer, UInt64 offset, UInt64 size);
        void SetIndexBuffer(IGPUBuffer buffer, GPUIndexFormat format, UInt64 offset, UInt64 size);
        
        void Draw(UInt32 vertexCount, UInt32 instanceCount, UInt32 firstVertex, UInt32 firstInstance);
        void DrawIndexed(UInt32 indexCount, UInt32 instanceCount, UInt32 firstIndex, Int32 baseVertex, UInt32 firstInstance);
        void DrawIndirect(IGPUBuffer indirectBuffer, UInt64 indirectOffset);
        void DrawIndexedIndirect(IGPUBuffer indirectBuffer, UInt64 indirectOffset);
        
        IGPURenderBundle Finish();
        IGPURenderBundle FinishWithDescriptor(GPURenderBundleDescriptor descriptor);
    };

    interface IGPURenderBundle
    {
        String Label;
    };

    interface IGPUQuerySet : Windows.Foundation.IClosable
    {
        String Label;
        GPUQueryType Type { get; };
        UInt32 Count { get; };
    };

    interface IGPUQueue
    {
        String Label;

        void Submit(IVectorView<IGPUCommandBuffer> commandBuffers);
        Windows.Foundation.IAsyncAction OnSubmittedWorkDone();
        
        void WriteBuffer(IGPUBuffer buffer, UInt64 bufferOffset, Windows.Storage.Streams.IBuffer data, UInt64 dataOffset, UInt64 size);
        void WriteTexture(IGPUTexture destination, Windows.Storage.Streams.IBuffer data, GPUExtent3D size);
    };

    // Additional types needed for render pass and compute pass
    struct GPUComputePassDescriptor {
        String Label;
    };

    [default_interface]
    runtimeclass GPURenderPassDescriptor
    {
        GPURenderPassDescriptor();
        String Label;
        IVectorView<GPURenderPassColorAttachment> ColorAttachments;
        GPURenderPassDepthStencilAttachment DepthStencilAttachment;
        IGPUQuerySet OcclusionQuerySet;
        UInt64 MaxDrawCount;
    };

    [default_interface]
    runtimeclass GPURenderPassColorAttachment
    {
        GPURenderPassColorAttachment();
        IGPUTextureView View;
        UInt32 DepthSlice;
        IGPUTextureView ResolveTarget;
        GPULoadOp LoadOp;
        GPUStoreOp StoreOp;
        GPUColor ClearValue;
    };

    [default_interface]
    runtimeclass GPURenderPassDepthStencilAttachment
    {
        GPURenderPassDepthStencilAttachment();
        IGPUTextureView View;
        GPULoadOp DepthLoadOp;
        GPUStoreOp DepthStoreOp;
        Single DepthClearValue;
        GPULoadOp StencilLoadOp;
        GPUStoreOp StencilStoreOp;
        UInt32 StencilClearValue;
        Boolean DepthReadOnly;
        Boolean StencilReadOnly;
    };

    enum GPULoadOp {
        Load,
        Clear
    };

    enum GPUStoreOp {
        Store,
        Discard
    };

    struct GPUColor {
        Double R;
        Double G;
        Double B;
        Double A;
    };

    enum GPUIndexFormat {
        Uint16,
        Uint32
    };

    struct GPUCommandBufferDescriptor {
        String Label;
    };

    struct GPURenderBundleDescriptor {
        String Label;
    };

    struct GPUTextureViewDescriptor {
        String Label;
        GPUTextureFormat Format;
        GPUTextureViewDimension Dimension;
        GPUTextureAspect Aspect;
        UInt32 BaseMipLevel;
        UInt32 MipLevelCount;
        UInt32 BaseArrayLayer;
        UInt32 ArrayLayerCount;
    };

    enum GPUTextureViewDimension {
        _1D,
        _2D,
        _2DArray,
        Cube,
        CubeArray,
        _3D
    };

    enum GPUTextureAspect {
        All,
        StencilOnly,
        DepthOnly
    };

    // Main interfaces
    interface IGPUAdapter
    {
        GPUSupportedLimits Limits { get; };
        IVectorView<GPUFeature> Features { get; };
        IGPUAdapterInfo Info { get; };

        Windows.Foundation.IAsyncOperation<IGPUDevice> RequestDevice();
        Windows.Foundation.IAsyncOperation<IGPUDevice> RequestDeviceWithDescriptor(GPUDeviceDescriptor descriptor);
    };

    interface IGPUAdapterInfo
    {
        String Vendor { get; };
        String Architecture { get; };
        String Device { get; };
        String Description { get; };
        UInt32 SubgroupMinSize { get; };
        UInt32 SubgroupMaxSize { get; };
        Boolean IsFallbackAdapter { get; };
    };

    interface IGPUDevice : Windows.Foundation.IClosable
    {
        IVectorView<GPUFeature> Features { get; };
        GPUSupportedLimits Limits { get; };
        IGPUAdapterInfo AdapterInfo { get; };
        IGPUQueue Queue { get; };
        String Label;

        // Device lost promise
        Windows.Foundation.IAsyncOperation<GPUDeviceLostInfo> Lost { get; };

        // Resource creation methods
        IGPUBuffer CreateBuffer(GPUBufferDescriptor descriptor);
        IGPUTexture CreateTexture(GPUTextureDescriptor descriptor);
        IGPUSampler CreateSampler();
        IGPUSampler CreateSamplerWithDescriptor(GPUSamplerDescriptor descriptor);
        IGPUExternalTexture ImportExternalTexture(GPUExternalTextureDescriptor descriptor);

        // Pipeline and binding creation
        IGPUBindGroupLayout CreateBindGroupLayout(GPUBindGroupLayoutDescriptor descriptor);
        IGPUPipelineLayout CreatePipelineLayout(GPUPipelineLayoutDescriptor descriptor);
        IGPUBindGroup CreateBindGroup(GPUBindGroupDescriptor descriptor);

        // Shader and pipeline creation
        IGPUShaderModule CreateShaderModule(GPUShaderModuleDescriptor descriptor);
        IGPUComputePipeline CreateComputePipeline(GPUComputePipelineDescriptor descriptor);
        IGPURenderPipeline CreateRenderPipeline(GPURenderPipelineDescriptor descriptor);
        Windows.Foundation.IAsyncOperation<IGPUComputePipeline> CreateComputePipelineAsync(GPUComputePipelineDescriptor descriptor);
        Windows.Foundation.IAsyncOperation<IGPURenderPipeline> CreateRenderPipelineAsync(GPURenderPipelineDescriptor descriptor);

        // Command recording
        IGPUCommandEncoder CreateCommandEncoder();
        IGPUCommandEncoder CreateCommandEncoderWithDescriptor(GPUCommandEncoderDescriptor descriptor);
        IGPURenderBundleEncoder CreateRenderBundleEncoder(GPURenderBundleEncoderDescriptor descriptor);

        // Query sets
        IGPUQuerySet CreateQuerySet(GPUQuerySetDescriptor descriptor);

        // Error handling
        void PushErrorScope(GPUErrorFilter filter);
        Windows.Foundation.IAsyncOperation<IGPUError> PopErrorScope();

        // Events
        event Windows.Foundation.TypedEventHandler<IGPUDevice, IGPUError> UncapturedError;
    };

    struct GPUDeviceDescriptor {
        String Label;
        IVectorView<GPUFeature> RequiredFeatures;
        // RequiredLimits would need a map-like structure
        GPUQueueDescriptor DefaultQueue;
    };

    [default_interface]
    runtimeclass GPU
    {
        GPU();
        Windows.Foundation.IAsyncOperation<IGPUAdapter> RequestAdapter();
        IGPUAdapter RequestAdapterSync(); // For synchronous version if needed
    }
}
