<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RestoreSources>
			https://api.nuget.org/v3/index.json;
			../WebGPUWinRT.Projection/nuget
		</RestoreSources>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<Platforms>AnyCPU;x64</Platforms>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<CsWinRTIncludes>WebGPUWinRT</CsWinRTIncludes>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.2.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\WebGPUWinRT\WebGPUWinRT.vcxproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="wgpu_native.dll">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

	<!--<ItemGroup>
	  <ProjectReference Include="..\WebGPUWinRT.Projection\WebGPUWinRT.Projection.csproj" />
	</ItemGroup>-->

	<!--<ItemGroup>
		<PackageReference Include="WebGPUWinRT" Version="0.0.7-prerelease" />
	</ItemGroup>-->

</Project>
